# mithril required
# store.js is required!

# https://jamesroberts.name/blog/2010/02/22/string-functions-for-javascript-trim-to-camel-case-to-dashed-and-to-underscore/
toCamelCase = (s) ->
  s.replace(/(\-[a-z])/g, ($1) -> return $1.toUpperCase().replace('-','') )

M = {
  MAX_AUTOGENERATED_COMPONENT_ID: 2048
  instances: {}
  types: {}
  mountToDom: () ->
    for typeName, componentType of M.types
      tagName = 'component-' + typeName
      console.log tagName

      ## https://stackoverflow.com/a/15342661/1760643
      #elements = document.querySelectorAll('[data-component]');
      elements = document.querySelectorAll(tagName);

      for element in elements
        if not element.id?.length
          # autogenerate id
          # TODO to separate function
          for i in [1 .. M.MAX_AUTOGENERATED_COMPONENT_ID]
            elementId = typeName + i
            if not M.instances[elementId]?
              element.id = elementId
              break

          if not element.id?.length
            console.log 'Unable to find new elementId for ' + tagName
            continue

        json_data = element.getAttribute('data')

        try
          instanceData = JSON.parse(json_data)
        catch e
          console.log 'Can\'t parse json - ' + json_data + ' - for ' + tagName
          continue

        instanceData ?= {}

        for i in [element.attributes.length - 1 .. 0]
          attr = element.attributes[i]
          if attr.name.match("^data-")
            dataKey = toCamelCase(attr.name.substr(5))
            console.log dataKey
            #console.log attr.name + ': ' + attr.value
            element.removeAttribute(attr.name)
            try
              instanceData[dataKey] = JSON.parse(attr.value)
            catch e
              #console.log 'Can\'t parse json - ' + attr.value + ' - for attr ' + attr.name + ' in  #' + element.id
              #continue
              instanceData[dataKey] = attr.value


        element.setAttribute 'data', JSON.stringify(instanceData)

        instanceData.type = typeName

        M.instances[element.id] = instanceData
        console.log(element.id)
}

window.uiComponents = M
